"""
agri_data.py - Static and Seed Data for AgriSense Agricultural Intelligence Platform
Includes certified data and agronomic best practices for farmers.
"""

CROPS_DATA = [
    {
        "id": "cotton",
        "name": "Cotton (Kapus)",
        "scientific_name": "Gossypium hirsutum / arboreum",
        "category": "Cash Crop / Fiber",
        "ideal_temp": "21 - 35°C",
        "ideal_humidity": "50 - 75%",
        "water_req_mm": "700 - 1200 mm",
        "soil_type": "Deep Black Cotton Soil (Vertisols)",
        "growing_season": "Kharif (June to January)",
        "major_varieties": ["Bollgard II (BG-II)", "Ajeet-155", "RCH-659", "PKV Rajat", "Suraj"],
        "critical_stages": [
            "Germination & Seedling (0-25 DAS)",
            "Square Formation (35-50 DAS)",
            "Flowering & Boll Setting (55-90 DAS)",
            "Boll Maturation & Bursting (90-150 DAS)",
        ],
    },
    {
        "id": "soybean",
        "name": "Soybean",
        "scientific_name": "Glycine max",
        "category": "Oilseed / Legume",
        "ideal_temp": "20 - 30°C",
        "ideal_humidity": "60 - 80%",
        "water_req_mm": "450 - 700 mm",
        "soil_type": "Well-drained Fertile Loam to Medium Black Soil",
        "growing_season": "Kharif (June to October)",
        "major_varieties": ["JS 335", "JS 9305", "JS 9560", "MACS 1407", "NRC 37"],
        "critical_stages": [
            "Germination (0-7 DAS)",
            "Vegetative & Nodulation (15-30 DAS)",
            "Flowering (35-50 DAS)",
            "Pod Filling & Maturation (50-85 DAS)",
        ],
    },
    {
        "id": "pigeon_pea",
        "name": "Pigeon Pea (Tur / Arhar)",
        "scientific_name": "Cajanus cajan",
        "category": "Pulse / Legume",
        "ideal_temp": "25 - 35°C",
        "ideal_humidity": "55 - 75%",
        "water_req_mm": "600 - 900 mm",
        "soil_type": "Deep Loamy & Black Soils with good drainage",
        "growing_season": "Kharif (June to January/February)",
        "major_varieties": ["BDN 711", "BSMR 736", "ICPL 87119 (Asha)", "PKV Tara", "Godavari"],
        "critical_stages": [
            "Branching (30-45 DAS)",
            "Flowering Initiation (90-110 DAS)",
            "Pod Development (120-140 DAS)",
            "Pod Maturity (150-180 DAS)",
        ],
    },
    {
        "id": "sugarcane",
        "name": "Sugarcane (Oos)",
        "scientific_name": "Saccharum officinarum",
        "category": "Cash Crop / Sugar",
        "ideal_temp": "24 - 38°C",
        "ideal_humidity": "70 - 85%",
        "water_req_mm": "1500 - 2500 mm",
        "soil_type": "Deep well-aerated Loam to Heavy Clay with high organic matter",
        "growing_season": "Suru (Jan-Feb), Adsali (July-Aug), Pre-seasonal (Oct-Nov)",
        "major_varieties": ["Co 86032 (Nira)", "CoM 0265 (Phule 265)", "MS 10001", "Co 92005"],
        "critical_stages": [
            "Germination (0-45 DAP)",
            "Tillering (45-120 DAP)",
            "Grand Growth (120-270 DAP)",
            "Ripening & Maturity (270-360 DAP)",
        ],
    },
    {
        "id": "citrus",
        "name": "Citrus (Nagpur Mandarin / Santra)",
        "scientific_name": "Citrus reticulata Blanco",
        "category": "Horticulture / Fruit",
        "ideal_temp": "15 - 38°C",
        "ideal_humidity": "50 - 70%",
        "water_req_mm": "900 - 1200 mm",
        "soil_type": "Light to medium black well-drained soil (depth >1m)",
        "growing_season": "Ambia Bahar (Jan-Feb bloom) & Mrig Bahar (June-July bloom)",
        "major_varieties": ["Nagpur Mandarin", "Kinnow", "Mosambi (Sweet Orange)"],
        "critical_stages": [
            "Stress Period / Bahar Treatment",
            "Flowering & Fruit Set",
            "Fruit Development (Marble to Golf-ball stage)",
            "Fruit Color Break & Maturation",
        ],
    },
]

DISEASES_DATA = [
    {
        "id": "dis-001",
        "name": "Soybean Rust",
        "scientific_name": "Phakopsora pachyrhizi",
        "pathogen": "Fungus (Basidiomycete)",
        "affected_crops": ["Soybean", "Pigeon Pea"],
        "severity": "Critical",
        "symptoms": "Tiny, yellowish-brown to dark brown lesions on the underside of leaves with volcano-like uredinia pustules. Rapid premature defoliation under high humidity.",
        "favorable_conditions": "Continuous canopy wetness >6 hours, temperatures between 18-28°C, and relative humidity >75%.",
        "chemical_control": "Spray Hexaconazole 5% EC @ 2 ml/L or Tebuconazole 25.9% EC @ 1.5 ml/L of water at the first sign of pustules.",
        "organic_control": "Foliar application of Trichoderma harzianum @ 5g/L or 5% Neem Seed Kernel Extract (NSKE) as prophylactic protection.",
    },
    {
        "id": "dis-002",
        "name": "Cotton Bacterial Blight (Blackarm)",
        "scientific_name": "Xanthomonas citri pv. malvacearum",
        "pathogen": "Bacteria",
        "affected_crops": ["Cotton (Kapus)"],
        "severity": "High",
        "symptoms": "Angular water-soaked spots on leaves bounded by veins, progressing to black lesions along main leaf veins and stems (blackarm phase). Boll rot with dark sunken lesions.",
        "favorable_conditions": "Frequent rain showers with warm winds (25-30°C) and relative humidity >80%.",
        "chemical_control": "Spray Copper Oxychloride 50% WP @ 2.5 g/L mixed with Streptocycline @ 1 g per 10 Liters of water.",
        "organic_control": "Seed treatment with Pseudomonas fluorescens @ 10g/kg seed; spray fermented butter-milk (khatta chhaas) 5% dilution.",
    },
    {
        "id": "dis-003",
        "name": "Citrus Gummosis & Phytophthora Root Rot",
        "scientific_name": "Phytophthora nicotianae / citrophthora",
        "pathogen": "Oomycete / Water Mold",
        "affected_crops": ["Citrus (Nagpur Mandarin / Santra)"],
        "severity": "High",
        "symptoms": "Profuse gum exudation on the trunk near the ground collar region, cracking of bark, yellowing and wilting of tree canopy, and feeder root decay.",
        "favorable_conditions": "Stagnant soil moisture, direct flood irrigation contacting tree trunks, heavy clay soils with poor drainage.",
        "chemical_control": "Scrape infected bark and apply Bordeaux paste (1:1:10). Soil drenching with Metalaxyl 8% + Mancozeb 64% WP @ 2.5 g/L.",
        "organic_control": "Trunk application of Trichoderma viride enriched farmyard manure; maintain ring basin irrigation avoiding stem contact.",
    },
]

PESTS_DATA = [
    {
        "id": "pest-001",
        "name": "Pink Bollworm",
        "scientific_name": "Pectinophora gossypiella",
        "order": "Lepidoptera (Gelechiidae)",
        "crops_affected": ["Cotton (Kapus)"],
        "severity": "Critical",
        "economic_threshold_level": "8 moths/trap/night for 3 consecutive days OR 10% rosette flowers / infested green bolls.",
        "symptoms_and_damage": "Larvae bore into squares and bolls, sealing entrance holes with excreta. Rosetted appearance of flowers ('twisted rosette'). Larvae feed on lint and immature seeds, causing stained lint, premature boll opening, and severe yield loss.",
        "biological_control": "Install 5-8 pheromone traps per hectare with Gossyplure septa. Release Trichogramma bactrae parasitoids @ 50,000 eggs/acre weekly. Apply Beauveria bassiana @ 5 g/L.",
        "chemical_control": "Apply Profenofos 50% EC @ 30 ml per 10 L water, or Chlorantraniliprole 18.5% SC @ 3 ml per 10 L water when ETL is breached. Rotate modes of action.",
    },
    {
        "id": "pest-002",
        "name": "Soybean Stem Borer (Stem Fly)",
        "scientific_name": "Melanagromyza sojae",
        "order": "Diptera (Agromyzidae)",
        "crops_affected": ["Soybean"],
        "severity": "High",
        "economic_threshold_level": "More than 10% infested plants or 1 fly per meter row during early vegetative stage.",
        "symptoms_and_damage": "Maggots enter petiole and bore through the pith inside the main stem. Plants exhibit wilting of top leaves, stunted growth, and zig-zag red tunneling inside the split stem.",
        "biological_control": "Seed treatment with Trichoderma viride @ 5g/kg. Spray 5% NSKE (Neem Seed Kernel Extract) at 15-20 days after germination.",
        "chemical_control": "Seed treatment with Thiamethoxam 30% FS @ 10 ml/kg. Foliar spray of Chlorantraniliprole 18.5% SC @ 3 ml/10L or Quinalphos 25% EC @ 20 ml/10L.",
    },
    {
        "id": "pest-003",
        "name": "Cotton Whitefly",
        "scientific_name": "Bemisia tabaci",
        "order": "Hemiptera (Aleyrodidae)",
        "crops_affected": ["Cotton (Kapus)", "Soybean", "Vegetables"],
        "severity": "Moderate to High",
        "economic_threshold_level": "6-8 nymphs/adults per leaf on lower foliage.",
        "symptoms_and_damage": "Adults and nymphs suck sap from leaf undersides, secreting honeydew that fosters black sooty mold. Acts as vector for Cotton Leaf Curl Virus (CLCuV).",
        "biological_control": "Install 8-10 yellow sticky traps per acre. Spray Verticillium lecanii @ 5 g/L of water.",
        "chemical_control": "Spray Diafenthiuron 50% WP @ 12 g per 10 Liters water, or Pyriproxyfen 10% EC @ 20 ml per 10 Liters.",
    },
]

OFFICERS_DATA = [
    {
        "id": "1",
        "name": "Dr. Gajanan Deshmukh",
        "role": "Senior Agricultural Entomologist",
        "dept": "Krishi Vigyan Kendra (KVK) Agricultural Research Center",
        "qualification": "Ph.D. Agricultural Entomology",
        "experience": "14 Yrs Gov Service",
        "category": "entomology",
        "phone": "18001801551",
        "wa": "919420000000",
        "rating": "4.9",
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuCHuAD4oDl-tSyT9WbJlb2b7Smep6AC-hQgtPqrYzVaCiY-RMt8ZiDvfcAJF1_pIlmvdVIqrr6TvvYlcosIQNr9Ld2GXJFnr-1qEQO9PdWD8igTD9vdsuNOcCY28SenpiMBoUFGFyNS10jU9BZqux7UuBhr1ap9MzCy9Gz4geBU1_kWoQKbbMhaKjHa1EbyThJJQlQZIosLErljSuCgCwWJMsA5mBNGd5e2soe6pAtVggT-wck3vxpu",
        "status": "Available Today (10 AM - 4:30 PM)",
        "specialty": "Pink Bollworm, Soybean Rust, Biological Parasitoids",
    },
    {
        "id": "2",
        "name": "Smt. Sunita More",
        "role": "Taluka Agriculture Officer (TAO)",
        "dept": "Taluka Agriculture Extension Office, Sector 1",
        "qualification": "M.Sc. Agronomy",
        "experience": "11 Yrs Gov Service",
        "category": "officers",
        "phone": "0721200022",
        "wa": "919420000022",
        "rating": "4.8",
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuDQfNA7Fg2WTYv5sAxroGQDZ2_qa05fJTnqqSwycco331aSfRZb5uEfNRtX5tIKeON7ESa6N6miIBolQXrM2WknMZUeKH6fCN5WGmGWKSeSglo4gBvPxEFX-7LSkBpyfeha2GS8LX8M3X0EtHOasVQGA80oKOoLtJm59R2SF0jX6lJyhuhAIzQDeKZA3vl-I--olxpTcQFi4jO_XKgHrg5pAAnrwdbIcjXeFAfZptn9RYW9_aAUrwXY",
        "status": "In Field Inspection (Eastern Sector)",
        "specialty": "Crop Insurance (PMFBY), Drip Subsidies, Certified Seeds",
    },
    {
        "id": "3",
        "name": "Shri Rajesh Belsare",
        "role": "Sub-Divisional Agriculture Officer (SDAO)",
        "dept": "Central Sub-Division Agriculture Department",
        "qualification": "B.Sc. Agriculture (Honours)",
        "experience": "18 Yrs Gov Service",
        "category": "officers",
        "phone": "0721200033",
        "wa": "919420000033",
        "rating": "4.9",
        "image": "https://lh3.googleusercontent.com/aida-public/AB6AXuA6bDK9QswgcG-qVkioIJyDtTekmy2OdvwNHxiUL1LOHomVdYr5GA8WTGiTW9RF1FT1q3uy1-MZuXI5o0BikgfxHppXLFZ74XMfc_T1O0AsyY_Fu3UzJGaPViVpLtYKYg6wKHx4X7S03eIDo3aAuZF_PAjMgZM44w_vALsjFCGuChbeYxpRrYlLqb292UWt0p2FR_C1Ki_d_uTBz3o2TTRUEf6sMNQjl228bLj_3ANVhRZtP7lmYMMb",
        "status": "Office Duty (Central HQ)",
        "specialty": "Watershed Development, Organic Certification, CIBRC Regulations",
    },
]

KENDRA_DEALERS = [
    {
        "id": "k1",
        "name": "Kisan Krishi Seva Kendra",
        "dealer": "Sureshji Tayade",
        "address": "Shop 4, Market Yard, Sector 1",
        "distance": "2.1 km away",
        "license": "LIC #AGRI-DEALER-2021-992 (Valid up to 2028)",
        "phone": "0721200000",
        "stocks": ["Neem Oil 10,000 PPM", "Pheromone Traps & Lures", "Profenofos 50% EC", "Trichoderma"],
        "badge": "Certified CIBRC Dealer",
        "coordinates": {"lat": 21.2415, "lng": 77.7485},
    },
    {
        "id": "k2",
        "name": "Shetkari Krishi Bhandar & Seeds",
        "dealer": "Anilrao Deshmukh",
        "address": "Central Market Square, Sector 2",
        "distance": "6.4 km away",
        "license": "LIC #AGRI-DEALER-2019-411 (Valid up to 2029)",
        "phone": "0721200001",
        "stocks": ["Yellow Sticky Traps", "Cold Pressed Azadirachtin", "Chlorantraniliprole", "Bio-fertilizers"],
        "badge": "Open Today",
        "coordinates": {"lat": 21.2988, "lng": 77.7012},
    },
    {
        "id": "k3",
        "name": "Kisan Suvidha Agro Kendra",
        "dealer": "Pramod Wankhede",
        "address": "Station Road, Sector 3",
        "distance": "11.8 km away",
        "license": "LIC #AGRI-DEALER-2022-108 (Valid up to 2027)",
        "phone": "0721200002",
        "stocks": ["Pheromone Lures", "Copper Oxychloride (COC)", "Hexaconazole 5% SC"],
        "badge": "In Stock",
        "coordinates": {"lat": 21.465, "lng": 78.263},
    },
]
